import {StyleSheet} from 'react-native';
import {
  BLACK_COLOR,
  GRAY_92,
  GRAY_LIGHT,
  ORANGE_DARK,
  ORANGE_EXTRA_LIGHT,
  PURPLE,
  PURPLE_EXTRA_LIGHT,
  TEXT_COLOR,
  WHITE,
} from '../../utils/colors/colors';
import {getDeviceHeight} from '../../utils/constants/commonFunctions';
import {
  MONTSERRAT_BOLD,
  MONTSERRAT_MEDIUM,
  MONTSERRAT_REGULAR,
  MONTSERRAT_SEMIBOLD,
} from '../../utils/styles/commonStyles';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: WHITE},
  image: {
    height: getDeviceHeight() * 0.2,
    borderRadius: 12,
    marginBottom: 15,
    margin: 24,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
  },
  rupees: {fontSize: 20, fontFamily: MONTSERRAT_REGULAR, color: BLACK_COLOR},
  name: {fontFamily: MONTSERRAT_BOLD, fontSize: 20, color: ORANGE_DARK},
  address: {fontFamily: MONTSERRAT_MEDIUM, color: BLACK_COLOR, fontSize: 12},
  content: {margin: 25},
  perMonth: {
    fontFamily: MONTSERRAT_REGULAR,
    fontSize: 10,
    marginStart: 5,
    textAlign: 'right',
  },
  security: {textAlign: 'right', marginTop: 5, marginHorizontal: 20},
  bookingId: {
    color: BLACK_COLOR,
    fontFamily: MONTSERRAT_BOLD,
    fontSize: 15,
    marginTop: 10,
  },
  idValue: {color: BLACK_COLOR, fontFamily: MONTSERRAT_REGULAR},
  details: {fontFamily: MONTSERRAT_BOLD, color: ORANGE_DARK, fontSize: 16},
  line: {backgroundColor: GRAY_92, height: 1},
  rowContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  contentRow: {paddingHorizontal: 20, paddingVertical: 10},
  paymentDetail: {fontSize: 16, paddingHorizontal: 20, paddingVertical: 10},
  bookingDetails: {fontSize: 16, paddingHorizontal: 20, paddingVertical: 10},
  scroll: {paddingBottom: 40},
  security_view: {
    backgroundColor: ORANGE_EXTRA_LIGHT,
    paddingVertical: 12,
    borderRadius: 10,
    paddingHorizontal: 8,
    marginTop: 14,
  },
  security_txt: {fontSize: 12, fontFamily: MONTSERRAT_MEDIUM},
  mapButton: {
    marginHorizontal: 18,
    backgroundColor: PURPLE_EXTRA_LIGHT,
    alignSelf: 'flex-start',
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderWidth: 0.6,
    borderRadius: 10,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mapText: {color: TEXT_COLOR, fontFamily: MONTSERRAT_SEMIBOLD, fontSize: 12},
  img_arrow: {height: 18, width: 18},
});
